micronaut:
  application:
    name: petpr
  metrics:
    enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
  server:
    port: 9070
netty:
  default:
    allocator:
      max-order: 3
